Rerun autoconf.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10785,6 +10785,11 @@ fi
 # Check whether --with-nicklen was given.
 if test "${with_nicklen+set}" = set; then
   withval=$with_nicklen;
+  if ! expr "$withval" + 0 >/dev/null 2>&1; then
+	{ { echo "$as_me:$LINENO: error: NICKLEN must be a numeric value" >&5
+echo "$as_me: error: NICKLEN must be a numeric value" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
   if test $withval -ge 50; then
 	NICKLEN=50
 	{ echo "$as_me:$LINENO: WARNING: NICKLEN has a hard limit of 50. Setting NICKLEN=50" >&5
